language: java

sudo : false

jdk:
  - openjdk10

install:
  - git clone https://github.com/hycos/cnetwork-api cnetwork-api && cd cnetwork-api && mvn install && cd ..
  - mvn clean package

after_success:
  - bash <(curl -s https://codecov.io/bash)
