language: java

sudo : false

jdk:
  - oraclejdk8

install:
  - git clone https://github.com/hycos/cnetwork-api && mvn install
  - mvn clean package

after_success:
  - bash <(curl -s https://codecov.io/bash)
